t2 = customtkinter.CTkLabel(master=l2,text="Take Attendance")
t2.place(relx=0.5, rely=0.9, anchor=tkinter.CENTER)
l3 = customtkinter.CTkFrame(master=w, width=200, height=220, corner_radius=15)
l3.place(relx=0.7, rely=0.3)
b3= customtkinter.CTkButton(master=l3, text="",command=enter_Encoding,image=photo_3)
b3.place(relx=0.5, rely=0.4,anchor=tkinter.CENTER)
t3 = customtkinter.CTkLabel(master=l3,text="Manage Encoding")
t3.place(relx=0.5, rely=0.9, anchor=tkinter.CENTER)
w.mainloop()
